### ISSUE TITLE
Disk usage module

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#124]
We need a way to check disk usage per node, sort of like OpsCenter provides. My proposal is to have a module which will trigger occasionally and fetch this information, we should check if Cassandra provides this over JMX.

**Comment by mgobec** [comment]
Cassandra exposes this metric:

```
org.apache.cassandra.metrics:type=ColumnFamily,name=TotalDiskSpaceUsed
```

which provides disk space used and there is such metric per keyspace. If we need used/total we either need to rely on os metrics or pull that data with diagnostics module from os itself.

**Comment by nbozic-zz** [comment]
@mgobec so we should close this or? What if you have many column families and you want to find out how much your Cassandra (as in full data folder) takes on disk

**Comment by mgobec** [comment]
@nbozic It outputs total and the per CF statistics. I will close it for now.
