### ISSUE TITLE
Cache reading of hostname 

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#136]
I have changed value in `/etc/hosts` and change was immediately visible. We want to cache this out and use cached hostname instead of reading it on every single measurement.

Or figure out how to use hostname opposed to `InetAddress.getLocalHost().getHostName()` which is doing reverse lookup by IP in `/etc/hosts` and picks up first value.

**Comment by mgobec** [comment]
There is also hostname inconsistency across modules. All modules need to use the same hostname and it should be a tagged field.

**Comment by mgobec** [comment]
Follow the conversation from #139
