### ISSUE TITLE
Move hostname tag handling to measurement creation

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#141]
When creating measurement we should pre-fill tags and fields with empty maps and we should add tag `hostname` since measurement without hostname tag does not make sense. Move whole hostname handling from modules to hostname creation.

**Comment by nbozic-zz** [comment]
@nivancevic @mgobec what do you think? Think part of initialization of measurement should be tag added with correct hostname.

**Comment by mgobec** [comment]
Makes sense to set hostname on measurement on creation because measurement has no context without a source (host).

**Comment by nbozic-zz** [comment]
Fixed in PR #140
