### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#15]
Lets do discussion here how to add integration tests (strategy for that).

**Comment by nbozic-zz** [comment]
@nivancevic Do we have now everything for this since we have integration test with embedded Cassandra? Or this is more for docker test with actual Cassandra?

**Comment by nivancevic** [comment]
As for the strategy, yes, we have now everything. It's only that we need to implement integration tests for core and reporters.
