### ISSUE TITLE
Get statement from prepared statement

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-diagnostics#177]
In order to trace statement get statement from prepared statement in query handler implementation.

**Comment by nbozic-zz** [comment]
@mgobec let's use this issue to write all details for tracing that we attempted, I will add mine and you can add yours.

**Comment by nbozic-zz** [comment]
Here is summary of my investigation:

- easiest way to test all methods is to use `ITConnector` integration test which brings up embedded Cassandra and to print extracted things in log (attempt and verify)
- `ResultMessage` is there in `processStatement` but it is not there in `extractStatement`, it could contain interesting stuff so might be worth investigating
- `QueryProcessor#getPrepared` is called before `processStatement`, driver is sending params and MD5 hash to server, and there `ParsedStatement.Prepared` is returned which is pulled from `preparedStatements` map which is private variable in QueryProcessor
- `prepare(queryString, queryState)` is called once by driver when application side prepares statement (session.prepare) so this can be used to collect list of prepared String statements and we need just variables than which are sent each time
- `SelectStatament/MutationStatament` have `RawStatement` as inner class which has `parameters`, `selectClause`, `whereClause` so if we can hook into it using ByteBuddy probably we can collect the puzzle

**Comment by nbozic-zz** [comment]
Branch is [here](https://github.com/smartcat-labs/cassandra-diagnostics/tree/nivancevic-tracing), what is missing:

- add test to verify that statement is traced
- add configuration to switch on and off tracing of statements (this can be heavy operation so allow to configure through parameters)

@nivancevic can you add here what is missing (in addition to what I listed) so Milan can take over?

**Comment by nivancevic** [comment]
- add guards for executing the tracing related code in `QueryProcessorWrapper`

**Comment by nbozic-zz** [comment]
@nivancevic added configuration to switch on and off tracing and added guards to tracing related code

What needs to be done for first version of tracing:

- rebase branch so we can merge
- make unit tests compile and run them to show green
- fix checkstyle
- make integration test against embedded cassandra 
- do everything only for 3.0

What needs to be done later on (create issues):
- migrate tracing code to 2.0 connector
- enable/disable tracing over API
- do feature tests
