### ISSUE TITLE
Compaction monitoring

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#182]
We are lacking good compaction monitoring solution. We want to have compaction monitoring module which will output same info as with `watch -d nodetool compactionstats`.

There is WIP on branch [dejan created](https://github.com/smartcat-labs/cassandra-diagnostics/tree/mijicd-compaction-monitoring) which can be used as starting point.

**Comment by mgobec** [comment]
Added in #188
