### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#202]
People are having hard time to install and test our solution. We should create installer which will work easy and simple. Here are nice to haves and after some investigation we should have concrete idea what can and cannot be done. This should be wrapped in shell script.

1. Select version of diagnostics (based on that download correct jar for core and commons)
2. Select reporter that you want to use (based on that download jars from bintray)
3. Select version of connector (based on that download jar for correct version)
4. Ask about modules which you want to use (check configuration and try to interactively ask about many of configurable things, if this proves to be hard for MVP we can just use default configuration)
5. Copy jars to lib folder of Cassandra
6. Copy `cassandra-diagnostics.yaml` to place where `cassandra.yaml` is
7. Add lines for custom java agent to `cassandra-env.sh`
8. Restart Cassandra process

Do these steps for each node, so first step can be actually to provide somehow IPs of Cassandra nodes.

**Comment by mgobec** [comment]
Here 4. is overkill since you need to supply cassandra-diagnostics.yaml configuration.

**Comment by nivancevic** [comment]
Deploying JARs as well as Cass restart depends on the actual Cass installation method (location of lib folders, the way Cass service is controlled, etc.). This info has to be provided to the installation script at the start.

**Comment by nbozic-zz** [comment]
@mgobec Cool way to do it, even though I think it will be hard for first iteration of installer, would be to ask Slow Query Module Y/N then when I hit Y to ask about threshold etc and generate yaml on the fly. If that is too much we should provide configuration yaml and ask about path or something.

**Comment by mgobec** [comment]
Implemented in #222
