### ISSUE TITLE
Kafka reporter

### ISSUE THREAD

**Issue by nbozic-zz** [smartcat-labs/cassandra-diagnostics#220]
We are starting to develop Sentinel infra to accept measurements. Can you double check KafkaReport is it ok after changes we did and can you check if it will work when we spin up Sentinel infra.

**Comment by nbozic-zz** [comment]
Check #228 as well while you review this

**Comment by nbozic-zz** [comment]
Also #227 which Nikola added

**Comment by mgobec** [comment]
Currently measurement is reported as:
* topic: measurement name
* partition key: hostname
* value: measurement json representation

At this moment it looks ok for the initial metrics push to Sentinel. Higher level of configurability should be considered going forward (topics, partitioning, serialization,...)

**Comment by nivancevic** [comment]
MetricsModule uses actual Cassandra metrics' names as destination Kafka topic name. It means that dozens of Kafka topics and consumers needed to exists in order to receive all measurements. Should we change the module behavior or modify the kafka reporter?

**Comment by mgobec** [comment]
We need to update metrics module to generate complex measurements instead of simple measurement for each metric collected.

**Comment by nivancevic** [comment]
Created a new issue for complex measurements in Metrics module (#246).
