### ISSUE TITLE
Fallback to default configuration if no external is provided and remove LogQueryReporter as default

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-diagnostics#23]
At the moment we are using LogQueryReporter if there is no configuration or faulty configuration. Do we want to fallback or just crash the app and make it obvious?

**Comment by nbozic-zz** [comment]
I would crash application if something is wrong with configuration. Falling back to log query reporter is masking the issue.

**Comment by nivancevic** [comment]
It makes sense to crash app if the given configuration is problematic. Also, the question is if a default configuration makes sense at all.

**Comment by nbozic-zz** [comment]
Nikola had a good suggestion to fallback to default configuration if no external configuration is provided and there we can define log query reporter as default. 

If you mess configuration up diagnostics startup should fail.

**Comment by nbozic-zz** [comment]
If misconfigured fail and if not provide just default (default is heartbeat with log reporter)

**Comment by mgobec** [comment]
Add default yaml configuration to resources in jar
