### ISSUE TITLE
Functional test `FTBasic` always passes

### ISSUE THREAD

**Issue by milannister** [smartcat-labs/cassandra-diagnostics#260]
In `FTBasic.test()` change `Assertions.assertThat(repairSessionsFound).isTrue();` to `Assertions.assertThat(repairSessionsFound).isFalse();` and run `mvn clean verify -P functional-test`. Test will pass.

That should not be the case.

**Comment by milannister** [comment]
The issue appears to be with BUILDANDDEPLOY.md, and not with the functional test (which is OK).

In order to activate basic profile `mvn clean verify -P functional-test,basic-ft` should be run, instead of `mvn clean verify -P functional-test`.

**Comment by nbozic-zz** [comment]
@milannister can you work on readme file inside PR which is open

**Comment by milannister** [comment]
@nbozic yes. I will fix this with the latest pull request.
