### ISSUE TITLE
Slow queries logged below threshold

### ISSUE THREAD

**Issue by mgobec** [smartcat-labs/cassandra-diagnostics#27]
When starting or stopping node, all slow queries are logged for a certain period of time.

@nivancevic Is this initialization issue?

**Comment by mgobec** [comment]
This should be retested with new implementation without guice

**Comment by nbozic-zz** [comment]
@nivancevic Did this again occurred when you tested with docker using FT.

**Comment by mgobec** [comment]
Not reproducible in new version
